### ISSUE TITLE
No provider for httpclient when running remote app in host 

### ISSUE THREAD

**Issue by ak274** [Coly010/example-nx-ng-mfe#2]
1) Added one lib in shared/data-access
2) Created one post service and added one  http request get method getPosts 
3) Inject the posts service in todo shell component
4) Imported required dependency  HttpClientModule in imports array of remote todo app so that when app will be open in its own url it should have the dependency.
5) Imported required dependency   HttpClientModule in app imports of static-host app so that its available when remote is being opened in shell/host app.

When running remote app standalone it works fine.

But when running app in host app it fails at runtime with error below:--

I have forked the example repo and produced the issue here:-- 

https://github.com/ak274/example-nx-ng-mfe

NullInjectorError: R3InjectorError(RemoteEntryModule)[PostService -> PostService -> HttpClient -> HttpClient -> HttpClient]: 
  NullInjectorError: No provider for HttpClient!

![image](https://user-images.githubusercontent.com/16129430/164186110-c5d921eb-c7ac-42a6-ad38-277d581ed851.png)

**Comment by ak274** [comment]
@Coly010 I feel shared modules are not working properly when using new setup  

 ​withModuleFederation​(​config​)​;

As I have made no changes in my project and it was working fine previously with old mfe configuration.

Looking forward to your input 🙂!

**Comment by Coly010** [comment]
Fixed by this: https://github.com/nrwl/nx/pull/9896
