### ISSUE TITLE
Question: NgRx implementation with module federation

### ISSUE THREAD

**Issue by Vevl** [Coly010/example-nx-ng-mfe#4]
Hey @Coly010,

Previously I was using module federation via [Manfred Steyer solution](https://www.npmjs.com/package/@angular-architects/module-federation) and NgRx was working just ok. After I updated to NXv14 I saw an opportunity to use a more readable approach with `@nrwl/angular/module-federation` but I run into an issue where I was unable to use `StoreModule.forFeature()` in remote app feature library.

Is there a way how to debug or check if NgRx is not a singleton across app? Because I think when I serve remote via HTTP server statically its not a singleton.

(btw if you have any idea how to extend this example I would love to help)

**Comment by Coly010** [comment]
Is your problem with adding NgRx to this repo? Or do you have a separate repo?

If it’s this, this is behind a few patch versions of Nx that I need to migrate to.

then when I do, I can also add NgRx to this to show it working. 


If it’s your own repo, check that you’re up to date on the latest version of Angular.

**Comment by Vevl** [comment]
I'm at version `"@nrwl/angular": "14.0.2"` and as soon as I imported `StoreModule.forRoot({})` to the remote app module it's no longer a problem but I assume this is because of a separate instance of ngrx maybe?
Do you think migration to the latest version can solve this problem?

**Comment by Coly010** [comment]
Yes, migration to latest should solve the problem

**Comment by Vevl** [comment]
Thanks, you were right.
